<?php

declare(strict_types=1);
namespace OCA\ERP\Db;
use OCP\AppFramework\Db\Entity;
/** @method string getDocumentType() @method void setDocumentType(string $value) @method string|null getSubject() @method void setSubject(?string $value) @method string|null getHeaderText() @method void setHeaderText(?string $value) @method string|null getIntroText() @method void setIntroText(?string $value) @method string|null getClosingText() @method void setClosingText(?string $value) @method string|null getFooterText() @method void setFooterText(?string $value) @method string|null getPaymentNote() @method void setPaymentNote(?string $value) @method string|null getDeliveryNote() @method void setDeliveryNote(?string $value) @method bool getShowUnitPrice() @method void setShowUnitPrice(bool $value) @method bool getShowDiscount() @method void setShowDiscount(bool $value) @method bool getShowVat() @method void setShowVat(bool $value) @method string|null getNumberPrefix() @method void setNumberPrefix(?string $value) @method int getUpdatedAt() @method void setUpdatedAt(int $value) */
class DocumentLayout extends Entity implements \JsonSerializable {
	protected string $documentType = 'quote'; protected ?string $subject = null; protected ?string $headerText = null; protected ?string $introText = null; protected ?string $closingText = null; protected ?string $footerText = null; protected ?string $paymentNote = null; protected ?string $deliveryNote = null; protected bool $showUnitPrice = true; protected bool $showDiscount = true; protected bool $showVat = true; protected ?string $numberPrefix = null; protected int $updatedAt = 0;
	public function __construct() { $this->addType('id', 'integer'); $this->addType('showUnitPrice', 'boolean'); $this->addType('showDiscount', 'boolean'); $this->addType('showVat', 'boolean'); $this->addType('updatedAt', 'integer'); }
	public function jsonSerialize(): array { return ['id'=>$this->getId(),'documentType'=>$this->getDocumentType(),'subject'=>$this->getSubject(),'headerText'=>$this->getHeaderText(),'introText'=>$this->getIntroText(),'closingText'=>$this->getClosingText(),'footerText'=>$this->getFooterText(),'paymentNote'=>$this->getPaymentNote(),'deliveryNote'=>$this->getDeliveryNote(),'showUnitPrice'=>$this->getShowUnitPrice(),'showDiscount'=>$this->getShowDiscount(),'showVat'=>$this->getShowVat(),'numberPrefix'=>$this->getNumberPrefix()]; }
}
